### PR TITLE
Add quick link for daily video quest

### PR DESCRIPTION
**Pull request by Lucki**
Adds a quick link to add a new post to the [In-Game Media forum section](https://eu.alienwarearena.com/forums/board/464/in-game-media-2)

### CODE REVIEW

**Review by thomas-ashcraft — APPROVED** [review]

**Comment by Rudokhvist** [comment]
I have another idea for this daily quest, but I need to test if it will work first. Main question is "if we add a video and then delete it, will it quest still be marked as finished?". Because, if answer is yes, we may add a configuration box to put a link to youtube  video, and use this video to finish as many such quests as needed, completely automatically.
My other concern is shitty awa login system, it often drops errors, and only way to fix them is re-login, and that will ruin whole automation system.

**Comment by thomas-ashcraft** [comment]
> Main question is "if we add a video and then delete it, will it quest still be marked as finished?"

I think, good chances that answer is yes. But need to be tested for sure. Would be really nice if someone did this.

But there is other question: if you delete a video from AWA, can you add the exact same video one more time?

> configuration box to put a link to youtube video

That a good idea in that context, because the same video link from thousands users can theoretically cause interference between users in some moment and also can be bothering in server logs (if someone ever watch them at AWA).

> My other concern is shitty awa login system, it often drops errors, and only way to fix them is re-login, and that will ruin whole automation system.

That crap is bothering people for many years. Personally I have to login through Steam. Didnt resolving a problem with remembering authentification, but resolving a problem with being half authentificated. I mean when site thinks that you are logged in (showing you avatar and stuff), but in fact not.

By the way, I have found that this API link you have discovered, returns very specific error in such half-authentificated situation:
```{"code":401,"error":"Authentication required"}```
So I think along with status fetching, theoretically can be made some implementation of session reseting, forcing user to log in again. Or at least show sticky message at the screen corner, that will tell a user that there is something wrong with authentification so re-login must be done.

Unfortunately real problem solving with sessions can be done only through proper server configuraion. So from client-side we can only forcing users to re-login.

**Comment by Lucki** [comment]
> > Main question is "if we add a video and then delete it, will it quest still be marked as finished?"
> 
> I think, good chances that answer is yes. But need to be tested for sure. Would be really nice if someone did this.

I've posted a video and then immediately deleted it again, it's still counted as completed through the API. Of course I had to re-login because of a CSRF-Token error.

**Comment by Rudokhvist** [comment]
>I've posted a video and then immediately deleted it again, it's still counted as completed through the API. 

Also, it's possible to add the same video again.

>So I think along with status fetching, theoretically can be made some implementation of session reseting, forcing user to log in again. Or at least show sticky message at the screen corner, that will tell a user that there is something wrong with authentification so re-login must be done.

I like this idea. It's quite annoying bug, so it would be nice to at least know when it happen.

**Comment by Lucki** [comment]
> I have found that this API link you have discovered, returns very specific error in such half-authentificated situation:
> `{"code":401,"error":"Authentication required"}`

I'm not sure about this. While I got the CSRF-Token error I could access the API (`/api/v1/users/arp/status`) without any problems.

Edit: While we're thinking about automatically posting stuff we can also think about the converse and be merry direction and test if the same applies to that task. We could then search for the daily spam thread and post/delete our messages there.

Edit2: Worked the same way.

#21

**Pull request merged**
